FROM artifactory.dep.devops.cmit.cloud:20101/docker/cassandra
MAINTAINER huhu.shi@hand-china.com
ADD glowroot-central /etc/glowroot-central
ADD admin-default.json /etc/glowroot-central/
ADD start.sh /


USER root

EXPOSE 7000 7001 7199 9042 9160 4000
CMD ["/bin/sh", "/start.sh"]