FROM cassandra
MAINTAINER huhu.shi@hand-china.com

ADD start-cassandra.sh /

USER root

RUN sed -i 's/rpc_address: localhost/rpc_address: 0.0.0.0/g' /etc/cassandra/cassandra.yaml
RUN sed -i 's/# broadcast_rpc_address/broadcast_rpc_address/g' /etc/cassandra/cassandra.yaml

EXPOSE 7000 7001 7199 9042 9160 4000
CMD ["/bin/bash", "/start-cassandra.sh"]