name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: cmit-docker-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set env TAG
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      - name: set image repository
        run: echo "IMAGE_REPO=artifactory.dep.devops.cmit.cloud:20101/${{env.DOCKER_NAME}}/fssc-glowroot:${{env.TAG}}" >> $GITHUB_ENV
      - name: docker login
        run: docker login artifactory.dep.devops.cmit.cloud:20101 -u ${{env.USER_NAME}} -p ${{env.PASSWORD}}
      - name: Build the Docker image
        run: docker build --progress=plain --no-cache . --file ${{env.PROJECT_PATH}}/Dockerfile-hap-all-in-one --label commit-id=${{env.GIT_COMMIT_ID}} --label branch=${{env.GIT_BRANCH}} --tag ${{env.IMAGE_REPO}} --build-arg PROJECT_PATH=${{env.PROJECT_PATH}}
      - name: docker push
        run: docker push ${{env.IMAGE_REPO}}
      - name: remove local docker image
        run: docker image rm -f ${{env.IMAGE_REPO}}